# name of the software
name: Sikker Digital Post .NET
siteUrlText: difi.github.io/difi-sikker-digital-post-klient-dotnet

# current version of the software
version: 1.2.5540.26013
# url of the download button
downloadUrl: https://www.nuget.org/packages/difi-sikker-digital-post-klient/
 
# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT

#baseurl: "/sikker-digital-post-net-klient" # the subpath of your site, e.g. /blog/
coreUrl: "/sikker-digital-post-klient-dotnet"
collections:
  doks:
    output: true

##Version handling
currentCollecion: "v1_2"
currentVersion: "1.3"
versions: ["1.2", "1.3"]

# Collection of versions
collections:
  v1_2:  
    output: true
    permalink: /v1.2/    
  v1_3:
    output: true
    permalink: /v1.3/
## End of Version handling

# list of additional links on the right of the top menu
headerLinks:
  - title: Om sikker digital post
    url: about.html
  - title: GitHub
    url: https://github.com/difi/sikker-digital-post-net-klient
  - title: Issues
    url: https://github.com/difi/sikker-digital-post-net-klient/issues

# github buttons
githubButton:
  user: difi
  repo: sikker-digital-post-net-klient

# twitter buttons
twitter:
  enabled: false
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: false
  profileUrl:

# google analytics
analytics:
  account:
  domain:

# DON'T MODIFY
highlight: rouge

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']

kramdown:
  input: GFM
